# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

def fib_sum():
    fib_sum = 2
    fib = [1,2]
    i = 0
    j = 1
    k = 0

    while k < 4000000:
        k = fib[i] + fib[j]
        if k % 2 == 0:
            fib_sum += k
        fib.append(k)
        i += 1
        j += 1

    return fib_sum